name: menu-server
on:
  - push
jobs:
  menu-server:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6
      - run: mvn compile
